numpy : Numerical python

In [1]:
distance = [12,13,14,15]
time = [1,2,3,4]
speed = distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [2]:
list(map(lambda x,y:x/y,distance,time))

[12.0, 6.5, 4.666666666666667, 3.75]

In [3]:
import numpy as np

In [5]:
distance = np.array(distance)
time = np.array(time)
speed = distance/time
speed

array([12.        ,  6.5       ,  4.66666667,  3.75      ])

In [8]:
l = [[1,2,3],[2,3,4],[3,4,5]]
arr = np.array(l)
arr[0][1]

2

In [10]:
l = [[1,2,3],[2,3,4],[3,4,5]]
arr = np.array([l])
arr[0][1][1]

3

In [11]:
arr.ndim

3

In [12]:
arr.shape

(1, 3, 3)

In [13]:
arr.size

9

In [14]:
arr.dtype

dtype('int32')

In [15]:
l = [[1,2,3],[2,3,4],[3,4,5]]
arr = np.array(l)
arr[1][1]

3

In [16]:
arr.shape

(3, 3)

In [26]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[12,13,14],[19,20,21],[16,17,18]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[12, 13, 14],
        [19, 20, 21],
        [16, 17, 18]]])

In [27]:
arr1.shape

(2, 3, 3)

In [28]:
arr1.dtype

dtype('int32')

In [29]:
arr1.ndim

3

In [30]:
arr1.size

18

In [31]:
type(arr1)

numpy.ndarray

In [32]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [33]:
arr[0][1]

2

In [34]:
arr[0][1] = 12

In [35]:
arr

array([[ 1, 12,  3],
       [ 2,  3,  4],
       [ 3,  4,  5]])

Operatin in numpy

In [36]:
arr

array([[ 1, 12,  3],
       [ 2,  3,  4],
       [ 3,  4,  5]])

In [37]:
arr**2

array([[  1, 144,   9],
       [  4,   9,  16],
       [  9,  16,  25]], dtype=int32)

In [38]:
arr+10

array([[11, 22, 13],
       [12, 13, 14],
       [13, 14, 15]])

In [45]:
arr[0][0] = 6.1

In [46]:
arr

array([[ 6, 12,  3],
       [ 2,  3,  4],
       [ 3,  4,  5]])

In [49]:
ax = np.array(arr,dtype = float)

In [50]:
ax

array([[ 6., 12.,  3.],
       [ 2.,  3.,  4.],
       [ 3.,  4.,  5.]])

In [51]:
a = np.array([[1,2.,3],[4,5,6],[8,9,7]])
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [8., 9., 7.]])

In [52]:
a[0][2] = 5

In [53]:
a

array([[1., 2., 5.],
       [4., 5., 6.],
       [8., 9., 7.]])

In [58]:
arr = np.array([[90,85,76,86,57],[78,90,59,88,58]])

In [59]:
arr

array([[90, 85, 76, 86, 57],
       [78, 90, 59, 88, 58]])

In [60]:
passing_marks = 60

In [61]:
arr>passing_marks

array([[ True,  True,  True,  True, False],
       [ True,  True, False,  True, False]])

In [62]:
arr[arr>passing_marks]

array([90, 85, 76, 86, 78, 90, 88])

In [63]:
arr.mean()

76.7

In [64]:
arr.sum()

767

In [65]:
np.median(arr)

81.5

In [67]:
arr[0].mean()

78.8

In [83]:
s = np.array([["Delhi","Mumbai","Pune","Indore","Chennai"],["Delhi","maha","maha","mp","TN"]])
s

array([['Delhi', 'Mumbai', 'Pune', 'Indore', 'Chennai'],
       ['Delhi', 'maha', 'maha', 'mp', 'TN']], dtype='<U7')

In [87]:
for i in s[0]:
    if len(i)>5:
        print(i)
    
    

Mumbai
Indore
Chennai


In [88]:
s

array([['Delhi', 'Mumbai', 'Pune', 'Indore', 'Chennai'],
       ['Delhi', 'maha', 'maha', 'mp', 'TN']], dtype='<U7')

In [89]:
s[0:2,1:3]

array([['Mumbai', 'Pune'],
       ['maha', 'maha']], dtype='<U7')

In [91]:
s[0,1:3]

array(['Mumbai', 'Pune'], dtype='<U7')

In [92]:
s[:,1:4]

array([['Mumbai', 'Pune', 'Indore'],
       ['maha', 'maha', 'mp']], dtype='<U7')

In [93]:
a = np.array([[[123,554,339],[890,780,670]]])
a

array([[[123, 554, 339],
        [890, 780, 670]]])

In [99]:
a[0][:,2]

array([339, 670])

In [100]:
a

array([[[123, 554, 339],
        [890, 780, 670]]])

In [101]:
b = a

In [102]:
b[0][0][0] = 120

In [103]:
b

array([[[120, 554, 339],
        [890, 780, 670]]])

In [104]:
a

array([[[120, 554, 339],
        [890, 780, 670]]])

In [105]:
c =a.view()

In [106]:
c

array([[[120, 554, 339],
        [890, 780, 670]]])

In [107]:
c[0][0][0] = 80
c

array([[[ 80, 554, 339],
        [890, 780, 670]]])

In [108]:
a

array([[[ 80, 554, 339],
        [890, 780, 670]]])

In [109]:
d = a.copy()
d

array([[[ 80, 554, 339],
        [890, 780, 670]]])

In [111]:
d[0][0][0] = 40

In [112]:
d

array([[[ 40, 554, 339],
        [890, 780, 670]]])

In [113]:
a

array([[[ 80, 554, 339],
        [890, 780, 670]]])

In [114]:
a = np.asarray([1,2,3])
a

array([1, 2, 3])