In [1]:
import numpy as np

In [2]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [3]:
print(range(3))

range(0, 3)


In [4]:
list(range(3))

[0, 1, 2]

In [6]:
range(3)

range(0, 3)

In [7]:
np.arange(3)

array([0, 1, 2])

In [14]:
np.arange(1.1,10.3,1)

array([ 1.1,  2.1,  3.1,  4.1,  5.1,  6.1,  7.1,  8.1,  9.1, 10.1])

WAP to create ur own range function

# linspace

In [15]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

# Logspace

In [16]:
np.logspace(1,10,20)

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.trace(a)

15

In [ ]:
Array and matrix differences:
    -matrix is a subclass of array

In [22]:
a = np.array([[[1,2],[3,4]]])
a.ndim

3

In [23]:
b = np.mat([[[1,2],[3,4]]])
b.ndim

ValueError: matrix must be 2-dimensional

In [24]:
a

array([[[1, 2],
        [3, 4]]])

In [25]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [26]:
a*b

array([[[ 5, 12],
        [21, 32]]])

In [27]:
a1 = np.mat(a)
b1 = np.mat(b)

In [29]:
a1*b1

matrix([[19, 22],
        [43, 50]])

In [30]:
a**2

array([[[ 1,  4],
        [ 9, 16]]], dtype=int32)

In [31]:
a1**2

matrix([[ 7, 10],
        [15, 22]])

In [32]:
from numpy import linalg

In [36]:
a

array([[[1, 2],
        [3, 4]]])

In [34]:
a_inv = np.linalg.inv(a)

In [35]:
a_inv

array([[[-2. ,  1. ],
        [ 1.5, -0.5]]])

In [37]:
np.dot(a,a_inv)

array([[[[1.00000000e+00, 1.11022302e-16]],

        [[0.00000000e+00, 1.00000000e+00]]]])