In [1]:
import numpy as np

# Random number generation using numpy

In [2]:
from numpy import random

In [3]:
a = np.random.rand(3,3)
a

array([[0.92806933, 0.64602154, 0.06228448],
       [0.63839272, 0.96591924, 0.68108651],
       [0.10624791, 0.67064568, 0.0313042 ]])

In [4]:
b = np.random.randn(3,3) #random number generation in standard normal distribution

In [5]:
b

array([[-1.22935687,  0.40294322,  1.08103384],
       [ 1.05063258, -0.43781815,  0.56768299],
       [-1.99499597,  0.68599622, -0.17774568]])

In [6]:
b.mean()

-0.0057364229417936246

In [7]:
b.std()

0.9967720312431388

In [8]:
c = np.random.randint(1,10,20)

In [9]:
c

array([3, 1, 8, 1, 3, 9, 8, 7, 6, 3, 7, 7, 3, 1, 8, 8, 6, 8, 4, 6])

In [10]:
c = np.random.randint(1,10,(3,3))

In [11]:
c

array([[3, 8, 6],
       [4, 5, 2],
       [2, 6, 6]])

In [12]:
c.sort(axis = 0)
c

array([[2, 5, 2],
       [3, 6, 6],
       [4, 8, 6]])

In [13]:
c.sort(axis = 1)
c

array([[2, 2, 5],
       [3, 6, 6],
       [4, 6, 8]])

kind = {"quiksort", "mergesort", "stable", "heapsort"}

quicksort : less time and less space - time and space 
compexity is less for quick sort

In [14]:
c.max()

8

In [15]:
c.min()

2

In [16]:
np.argmax(c) # index value of max number

8

In [17]:
np.argmin(c) # index value of min number

0

In [19]:
d = np.random.randint(100,400,(3,3))

In [20]:
d

array([[205, 209, 323],
       [127, 116, 367],
       [312, 150, 269]])

In [21]:
d.argmax(axis = 0) # all index value of max number in column)

array([2, 0, 1], dtype=int64)

In [22]:
d.argmin(axis = 0)  # all index value of min number in column)

array([1, 1, 2], dtype=int64)

In [23]:
d.argmax(axis = 1) # all index value of max number in raw)

array([2, 2, 0], dtype=int64)

In [24]:
d.argmin(axis = 1)  # all index value of min number in raw)

array([0, 1, 1], dtype=int64)

In [25]:
np.cumsum([1,2,3,4,5,6,7,8,9])

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [26]:
np.cumsum([[1,2,3],[5,8,9]])

array([ 1,  3,  6, 11, 19, 28], dtype=int32)