In [1]:
import numpy as np

In [2]:
a = np.array([1,4,9,16,25,36,49,64,81,100])
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [3]:
np.sqrt(a)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [4]:
np.sin(a)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175,
       -0.99177885, -0.95375265,  0.92002604, -0.62988799, -0.50636564])

In [5]:
from numpy import pi

In [6]:
np.sin(pi)

1.2246467991473532e-16

In [7]:
np.sin(pi/2)

1.0

In [8]:
np.cos(pi/4)

0.7071067811865476

In [10]:
a = np.array([12.45,3.23,15.67,-9.17])
np.floor(a)


array([ 12.,   3.,  15., -10.])

In [11]:
np.ceil(a)

array([13.,  4., 16., -9.])

In [13]:
a = np.array([1,4,9,16,25,36,49,64,81,100])
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
np.log(a)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.58351894, 3.8918203 , 4.15888308, 4.39444915, 4.60517019])

In [15]:
b = np.log(a)

In [16]:
b

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.58351894, 3.8918203 , 4.15888308, 4.39444915, 4.60517019])

In [17]:
np.exp(b)

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [18]:
np.std(a)

32.41990129534635

In [19]:
np.mean(a)

38.5

In [20]:
np.median(a)

30.5

In [21]:
np.var(a)

1051.05

# Shape Manipulation :
    

In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9])
np.reshape(arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.resize(arr,(9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [32]:
resize(arr,(9,1))

NameError: name 'resize' is not defined

In [27]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr.resize((3,3))

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.ravel(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Broadcasting

In [37]:
b = np.array([1,2,3,4,5,6,7,8,9])
b*2


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
b*2.0

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [39]:
b-0.002

array([0.998, 1.998, 2.998, 3.998, 4.998, 5.998, 6.998, 7.998, 8.998])

In [40]:
b+23

array([24, 25, 26, 27, 28, 29, 30, 31, 32])

# Methods:
    fromfunction
    fromiter
    fromsting

In [41]:
np.fromfunction(lambda x,y:x==y,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [43]:
np.fromfunction(lambda x,y:x>y,(3,3))

array([[False, False, False],
       [ True, False, False],
       [ True,  True, False]])

In [44]:
np.fromfunction(lambda x,y:x+y,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [45]:
np.fromiter([1,2,3,4,5],dtype = int)

array([1, 2, 3, 4, 5])

In [46]:
np.fromstring("1 2 3 4 5 6 7 8  9", sep = " ",dtype = int) 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Array of Zeros:

In [47]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.ones((3,3))+6

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [50]:
np.two((3,3))

AttributeError: module 'numpy' has no attribute 'two'

In [62]:
 np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
 np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [53]:
np.diag(a)

array([1., 1., 1.])

In [54]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.diag(a)

array([1, 5, 9])

In [56]:
np.diag(a,k=1)

array([2, 6])

In [57]:
np.diag(a,k=2)

array([3])

In [58]:
np.diag(a,k=3)

array([], dtype=int32)

In [59]:
np.diag(a,k=-1)

array([4, 8])

In [60]:
np.diag(a,k=-2)

array([7])

In [61]:
np.diag(a,k=-3)

array([], dtype=int32)

In [64]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [65]:
np.tri(3,k=1)

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
np.tri(3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [67]:
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [68]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [69]:
np.diagflat(a)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [70]:
np.diagflat([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])